image: condaforge/mambaforge:24.3.0-0
tasks:
  - name: initialize
    command: |
      export CONDA_ALWAYS_YES="true"

      conda create --name env
      source ~/.bashrc
      clear
      conda activate env
      conda config --add channels defaults
      conda config --add channels bioconda
      conda config --add channels conda-forge
      conda config --set channel_priority strict
      conda install -c bioconda bowtie

      unset CONDA_ALWAYS_YES 
  