image: condaforge/mambaforge:24.3.0-0
tasks:
  - name: initialize
    command: |
      export CONDA_ALWAYS_YES="true"

      conda env create -f environment.yml
      echo "conda activate env" >> ~/.bashrc
      source ~/.bashrc

      unset CONDA_ALWAYS_YES 

      clear
    
  