<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bio-informatica groepswerk handleiding</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="cursus_files/libs/clipboard/clipboard.min.js"></script>
<script src="cursus_files/libs/quarto-html/quarto.js"></script>
<script src="cursus_files/libs/quarto-html/popper.min.js"></script>
<script src="cursus_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="cursus_files/libs/quarto-html/anchor.min.js"></script>
<link href="cursus_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cursus_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="cursus_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="cursus_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="cursus_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introductie" id="toc-introductie" class="nav-link active" data-scroll-target="#introductie">Introductie</a></li>
  <li><a href="#vs-code-op-de-vlaamse-supercomputer-centrum-infrastructuur" id="toc-vs-code-op-de-vlaamse-supercomputer-centrum-infrastructuur" class="nav-link" data-scroll-target="#vs-code-op-de-vlaamse-supercomputer-centrum-infrastructuur">VS Code op de Vlaamse Supercomputer Centrum infrastructuur</a></li>
  <li><a href="#introductie-tot-linux-shellbash" id="toc-introductie-tot-linux-shellbash" class="nav-link" data-scroll-target="#introductie-tot-linux-shellbash">Introductie tot Linux Shell/Bash</a>
  <ul class="collapse">
  <li><a href="#wat-is-een-shell" id="toc-wat-is-een-shell" class="nav-link" data-scroll-target="#wat-is-een-shell">Wat is een Shell?</a></li>
  <li><a href="#basisbegrippen" id="toc-basisbegrippen" class="nav-link" data-scroll-target="#basisbegrippen">Basisbegrippen</a></li>
  <li><a href="#basisopdrachten" id="toc-basisopdrachten" class="nav-link" data-scroll-target="#basisopdrachten">Basisopdrachten</a>
  <ul class="collapse">
  <li><a href="#pwd-print-working-directory" id="toc-pwd-print-working-directory" class="nav-link" data-scroll-target="#pwd-print-working-directory"><code>pwd</code> (Print Working Directory)</a></li>
  <li><a href="#ls-list" id="toc-ls-list" class="nav-link" data-scroll-target="#ls-list"><code>ls</code> (List)</a></li>
  <li><a href="#cd-change-directory" id="toc-cd-change-directory" class="nav-link" data-scroll-target="#cd-change-directory"><code>cd</code> (Change Directory)</a></li>
  <li><a href="#mkdir-make-directory" id="toc-mkdir-make-directory" class="nav-link" data-scroll-target="#mkdir-make-directory"><code>mkdir</code> (Make Directory)</a></li>
  <li><a href="#cp-copy" id="toc-cp-copy" class="nav-link" data-scroll-target="#cp-copy"><code>cp</code> (Copy)</a></li>
  <li><a href="#mv-move" id="toc-mv-move" class="nav-link" data-scroll-target="#mv-move"><code>mv</code> (Move)</a></li>
  <li><a href="#rm-remove" id="toc-rm-remove" class="nav-link" data-scroll-target="#rm-remove"><code>rm</code> (Remove)</a></li>
  <li><a href="#cat-concatenate" id="toc-cat-concatenate" class="nav-link" data-scroll-target="#cat-concatenate"><code>cat</code> (Concatenate)</a></li>
  <li><a href="#echo" id="toc-echo" class="nav-link" data-scroll-target="#echo"><code>echo</code></a></li>
  </ul></li>
  <li><a href="#opdrachtstructuur" id="toc-opdrachtstructuur" class="nav-link" data-scroll-target="#opdrachtstructuur">Opdrachtstructuur</a></li>
  <li><a href="#tips" id="toc-tips" class="nav-link" data-scroll-target="#tips">Tips</a></li>
  <li><a href="#oefenopdrachten" id="toc-oefenopdrachten" class="nav-link" data-scroll-target="#oefenopdrachten">Oefenopdrachten</a></li>
  </ul></li>
  <li><a href="#kwaliteitscontrole-met-fastqc" id="toc-kwaliteitscontrole-met-fastqc" class="nav-link" data-scroll-target="#kwaliteitscontrole-met-fastqc">Kwaliteitscontrole met FastQC</a>
  <ul class="collapse">
  <li><a href="#doel" id="toc-doel" class="nav-link" data-scroll-target="#doel">Doel</a></li>
  <li><a href="#het-fastq-formaat" id="toc-het-fastq-formaat" class="nav-link" data-scroll-target="#het-fastq-formaat">Het FASTQ-formaat</a>
  <ul class="collapse">
  <li><a href="#wat-is-fastq" id="toc-wat-is-fastq" class="nav-link" data-scroll-target="#wat-is-fastq">Wat is FASTQ?</a></li>
  <li><a href="#voorbeeld-van-een-fastq-entry" id="toc-voorbeeld-van-een-fastq-entry" class="nav-link" data-scroll-target="#voorbeeld-van-een-fastq-entry">Voorbeeld van een FASTQ-entry</a></li>
  <li><a href="#structuur-van-een-fastq-bestand" id="toc-structuur-van-een-fastq-bestand" class="nav-link" data-scroll-target="#structuur-van-een-fastq-bestand">Structuur van een FASTQ-bestand</a></li>
  </ul></li>
  <li><a href="#opdrachten" id="toc-opdrachten" class="nav-link" data-scroll-target="#opdrachten">Opdrachten</a></li>
  <li><a href="#het-interpreteren-van-het-fastqc-html-rapport" id="toc-het-interpreteren-van-het-fastqc-html-rapport" class="nav-link" data-scroll-target="#het-interpreteren-van-het-fastqc-html-rapport">Het interpreteren van het FastQC HTML-rapport</a></li>
  <li><a href="#opdrachtvragen" id="toc-opdrachtvragen" class="nav-link" data-scroll-target="#opdrachtvragen">Opdrachtvragen:</a></li>
  </ul></li>
  <li><a href="#read-mapping-met-bwa" id="toc-read-mapping-met-bwa" class="nav-link" data-scroll-target="#read-mapping-met-bwa">Read Mapping met BWA</a>
  <ul class="collapse">
  <li><a href="#doel-1" id="toc-doel-1" class="nav-link" data-scroll-target="#doel-1">Doel</a></li>
  <li><a href="#sam-formaat-sequence-alignmentmap" id="toc-sam-formaat-sequence-alignmentmap" class="nav-link" data-scroll-target="#sam-formaat-sequence-alignmentmap">SAM-formaat (Sequence Alignment/Map)</a>
  <ul class="collapse">
  <li><a href="#wat-is-sam" id="toc-wat-is-sam" class="nav-link" data-scroll-target="#wat-is-sam">Wat is SAM?</a></li>
  <li><a href="#structuur-van-een-sam-bestand" id="toc-structuur-van-een-sam-bestand" class="nav-link" data-scroll-target="#structuur-van-een-sam-bestand">Structuur van een SAM-bestand</a></li>
  <li><a href="#voorbeeld-van-een-sam-entry" id="toc-voorbeeld-van-een-sam-entry" class="nav-link" data-scroll-target="#voorbeeld-van-een-sam-entry">Voorbeeld van een SAM-entry</a></li>
  <li><a href="#uitleg" id="toc-uitleg" class="nav-link" data-scroll-target="#uitleg">Uitleg</a></li>
  </ul></li>
  <li><a href="#opdrachten-1" id="toc-opdrachten-1" class="nav-link" data-scroll-target="#opdrachten-1">Opdrachten</a></li>
  <li><a href="#bam-formaat-binary-alignmentmap" id="toc-bam-formaat-binary-alignmentmap" class="nav-link" data-scroll-target="#bam-formaat-binary-alignmentmap">BAM-formaat (Binary Alignment/Map)</a>
  <ul class="collapse">
  <li><a href="#wat-is-bam" id="toc-wat-is-bam" class="nav-link" data-scroll-target="#wat-is-bam">Wat is BAM?</a></li>
  <li><a href="#kenmerken-van-bam" id="toc-kenmerken-van-bam" class="nav-link" data-scroll-target="#kenmerken-van-bam">Kenmerken van BAM</a></li>
  <li><a href="#voorbeeld" id="toc-voorbeeld" class="nav-link" data-scroll-target="#voorbeeld">Voorbeeld</a></li>
  </ul></li>
  <li><a href="#opdracht-2" id="toc-opdracht-2" class="nav-link" data-scroll-target="#opdracht-2">Opdracht 2</a></li>
  <li><a href="#opdrachtvragen-1" id="toc-opdrachtvragen-1" class="nav-link" data-scroll-target="#opdrachtvragen-1">Opdrachtvragen:</a></li>
  </ul></li>
  <li><a href="#variant-calling-met-mutect2" id="toc-variant-calling-met-mutect2" class="nav-link" data-scroll-target="#variant-calling-met-mutect2">Variant Calling met Mutect2</a>
  <ul class="collapse">
  <li><a href="#vcf-formaat-variant-call-format" id="toc-vcf-formaat-variant-call-format" class="nav-link" data-scroll-target="#vcf-formaat-variant-call-format">VCF-formaat (Variant Call Format)</a>
  <ul class="collapse">
  <li><a href="#wat-is-vcf" id="toc-wat-is-vcf" class="nav-link" data-scroll-target="#wat-is-vcf">Wat is VCF?</a></li>
  <li><a href="#structuur-van-een-vcf-bestand" id="toc-structuur-van-een-vcf-bestand" class="nav-link" data-scroll-target="#structuur-van-een-vcf-bestand">Structuur van een VCF-bestand</a></li>
  <li><a href="#voorbeeld-van-een-vcf-entry" id="toc-voorbeeld-van-een-vcf-entry" class="nav-link" data-scroll-target="#voorbeeld-van-een-vcf-entry">Voorbeeld van een VCF-entry</a></li>
  <li><a href="#uitleg-1" id="toc-uitleg-1" class="nav-link" data-scroll-target="#uitleg-1">Uitleg</a></li>
  </ul></li>
  <li><a href="#opdrachten-2" id="toc-opdrachten-2" class="nav-link" data-scroll-target="#opdrachten-2">Opdrachten</a></li>
  <li><a href="#opdrachtvragen-2" id="toc-opdrachtvragen-2" class="nav-link" data-scroll-target="#opdrachtvragen-2">Opdrachtvragen:</a></li>
  <li><a href="#opdrachtvragen-deel-2" id="toc-opdrachtvragen-deel-2" class="nav-link" data-scroll-target="#opdrachtvragen-deel-2">Opdrachtvragen deel 2:</a></li>
  </ul></li>
  <li><a href="#variant-annotatie-met-snpeff" id="toc-variant-annotatie-met-snpeff" class="nav-link" data-scroll-target="#variant-annotatie-met-snpeff">Variant Annotatie met SnpEff</a>
  <ul class="collapse">
  <li><a href="#het-snpeff-html-rapport-begrijpen" id="toc-het-snpeff-html-rapport-begrijpen" class="nav-link" data-scroll-target="#het-snpeff-html-rapport-begrijpen">Het SnpEff HTML-rapport begrijpen</a>
  <ul class="collapse">
  <li><a href="#a.-algemene-statistieken-sectie" id="toc-a.-algemene-statistieken-sectie" class="nav-link" data-scroll-target="#a.-algemene-statistieken-sectie">A. Algemene Statistieken Sectie</a></li>
  </ul></li>
  <li><a href="#opdrachtvragen-3" id="toc-opdrachtvragen-3" class="nav-link" data-scroll-target="#opdrachtvragen-3">Opdrachtvragen</a>
  <ul class="collapse">
  <li><a href="#deel-1-basis-statistieken" id="toc-deel-1-basis-statistieken" class="nav-link" data-scroll-target="#deel-1-basis-statistieken">Deel 1: Basis Statistieken</a></li>
  <li><a href="#deel-2-variant-effects-analyse" id="toc-deel-2-variant-effects-analyse" class="nav-link" data-scroll-target="#deel-2-variant-effects-analyse">Deel 2: Variant Effects Analyse</a></li>
  <li><a href="#deel-3-genoomregios" id="toc-deel-3-genoomregios" class="nav-link" data-scroll-target="#deel-3-genoomregios">Deel 3: Genoomregio’s</a></li>
  <li><a href="#deel-4-codon-veranderingen" id="toc-deel-4-codon-veranderingen" class="nav-link" data-scroll-target="#deel-4-codon-veranderingen">Deel 4: Codon Veranderingen</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#variant-filtering-met-snpsift" id="toc-variant-filtering-met-snpsift" class="nav-link" data-scroll-target="#variant-filtering-met-snpsift">Variant filtering met SnpSift</a>
  <ul class="collapse">
  <li><a href="#opdrachtvragen-4" id="toc-opdrachtvragen-4" class="nav-link" data-scroll-target="#opdrachtvragen-4">Opdrachtvragen</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="cursus.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bio-informatica groepswerk handleiding</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introductie" class="level1">
<h1>Introductie</h1>
<p>Somatische varianten zijn genetische veranderingen die niet overgeërfd zijn, maar tijdens iemands leven in specifieke cellen ontstaan. Deze varianten zijn vooral belangrijk in de context van kanker, waar ze een cruciale rol spelen bij het ontstaan en de progressie van de ziekte. Het doel van somatische variant calling is om deze niet-geërfde mutaties te identificeren in DNA sequencing data van tumoren en andere stalen.</p>
<p>Dit proces omvat:</p>
<ol type="1">
<li>Sequencing van tumorweefsel of bloedcellen van een patiënt.</li>
<li>Alignment van de sequentiedata aan een referentiegenoom.</li>
<li>Identificatie van posities waar de tumorsequentie verschilt van het referentiegenoom. Dit noemen we varianten.</li>
<li>Filteren van de gevonden varianten om prognostisch, diagnostisch of therapeutisch relevante varianten te vinden.</li>
</ol>
<p>Het belang van somatische variant calling ligt in verschillende gebieden:</p>
<ul>
<li><strong>Kankerdiagnostiek:</strong> Het helpt bij het identificeren van de specifieke mutaties die een rol spelen in een individuele tumor.</li>
<li><strong>Gepersonaliseerde behandeling:</strong> Kennis van de somatische varianten kan helpen bij het kiezen van de meest effectieve behandeling voor een patiënt.</li>
<li><strong>Onderzoek:</strong> Het draagt bij aan ons begrip van de genetische basis van kanker en andere ziekten.</li>
<li><strong>Monitoring:</strong> Het kan worden gebruikt om de evolutie van een tumor in de tijd te volgen en de respons op behandeling te evalueren.</li>
</ul>
<p>In dit groepswerk doorlopen we de stappen die nodig zijn om somatische variant calling uit te voeren. We leren de basisprincipes van sequentieanalyse en specifieke uitdagingen van het identificeren van somatische mutaties. Hierbij reflecteren we bij elke stap over de verkregen resultaten.</p>
</section>
<section id="vs-code-op-de-vlaamse-supercomputer-centrum-infrastructuur" class="level1">
<h1>VS Code op de Vlaamse Supercomputer Centrum infrastructuur</h1>
<p>Om de bio-informatica stappen uit te voeren in dit groepswerk gaan we gebruik maken van de VSC (Vlaamse Supercomputer Centrum) infrastructuur. We kunnen de VSC infrastructuur op verschillende manieren benaderen. De meest gebruiksvriendelijke manier is het <em>KU Leuven OnDemand</em> platform. Om in te loggen op dit platform doorloop je volgende stappen:</p>
<ol type="1">
<li>Surf met je browser naar <a href="https://ondemand.hpc.kuleuven.be/">https://ondemand.hpc.kuleuven.be</a></li>
<li>Kies hier de optie om in te loggen met een VSC account: “Partner organizations: VSC account”</li>
<li>Log in met je UHasselt account</li>
<li>Bij de vraag “Authorize vsc-challenge?” antwoord je “Authorize”</li>
</ol>
<p>Je bent nu ingelogd op het <em>KU Leuven OnDemand</em> platform. Hiermee kan je vanuit je webbrowser een aantal populaire applicaties opstarten op de Vlaamse SuperComputer. Meer achtergrond kan je vinden in de <a href="https://docs.vscentrum.be/leuven/services/openondemand.html">handleiding</a>.</p>
<p>Voor het groepswerk gaan we gebruik maken van de Visual Studio Code (VS Code) applicatie. Dit is een populaire applicatie om code te schrijven die een ingebouwde bestands browser en <em>terminal</em> vensters heeft. Om VS Code te starten via het OnDemand platform doorloop je de volgende stappen.</p>
<ol type="1">
<li>Klik op het “code-server” icoon.</li>
<li>Er verschijnt een formulier met een aantal opties. Controleer volgende opties en pas aan indien nodig.
<ul>
<li><strong>Account:</strong> lp_h_edu_bioinformatics_2024</li>
<li><strong>Number of hours:</strong> 1 (of meer als je langer wenst te werken aan de opdracht)</li>
<li><strong>Required memory per core in megabytes:</strong>: 6800</li>
</ul></li>
<li>Klik op “Launch”</li>
<li>Een overzicht van jouw recente sessies verschijnt met bovenaan de VS Code sessie met status “Queued”</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="cursus_images/ondemand_queue.png" class="img-fluid figure-img"></p>
<figcaption>Queued</figcaption>
</figure>
</div>
<p>Nu moet je even wachten tot de VS Code sessie gestart is. Normaal duurt dit maar enkele seconden. Het zou mogelijk zijn dat je ook wat langer moet wachten als de VSC infrastructuur druk bezet is. Wanneer de sessie gestart is verschijnt “Running” en wordt het kader groen:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="cursus_images/ondemand_ready.png" class="img-fluid figure-img"></p>
<figcaption>Ready</figcaption>
</figure>
</div>
<p>Klik nu op “Connect to Visual Studio Code”. De VS Code interface verschijnt.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="cursus_images/vscode_home.png" class="img-fluid figure-img"></p>
<figcaption>Alt text</figcaption>
</figure>
</div>
<blockquote class="blockquote">
<p>De sessie op de VSC cluster zal blijven openstaan tot de gevraagde tijd voorbij is of de sessie manueel gestopt wordt (rode “cancel” knop). Als je klaar bent met werken en de sessie toch laat openstaan gaat de VSC cluster onnodig gereserveerd worden en zullen andere gebruikers nodeloos moeten wachten. Sluit daarom de sessie af als je eerder klaar bent met werken dan de gevraagde tijd. Je kan steeds een nieuwe sessie starten!</p>
</blockquote>
</section>
<section id="introductie-tot-linux-shellbash" class="level1">
<h1>Introductie tot Linux Shell/Bash</h1>
<p>In dit groepswerk zullen we verschillende Linux</p>
<section id="wat-is-een-shell" class="level2">
<h2 class="anchored" data-anchor-id="wat-is-een-shell">Wat is een Shell?</h2>
<p>Een shell is een programma dat een interface biedt voor gebruikers om met het besturingssysteem te communiceren. De meest voorkomende shell in Linux-systemen heet Bash (Bourne Again SHell). Wanneer je de opdrachtregel gebruikt, typ je opdrachten in de shell.</p>
</section>
<section id="basisbegrippen" class="level2">
<h2 class="anchored" data-anchor-id="basisbegrippen">Basisbegrippen</h2>
<ol type="1">
<li><p><strong>Opdrachtprompt</strong>: Hier typ je je opdrachten. Het eindigt meestal met een <code>$</code>-teken.</p></li>
<li><p><strong>Opdrachten</strong>: Dit zijn instructies die je aan de computer geeft.</p></li>
<li><p><strong>Argumenten</strong>: Aanvullende informatie die je aan een opdracht geeft.</p></li>
<li><p><strong>Opties</strong>: Wijzigen het gedrag van opdrachten, meestal beginnend met een streepje (<code>-</code>).</p></li>
</ol>
</section>
<section id="basisopdrachten" class="level2">
<h2 class="anchored" data-anchor-id="basisopdrachten">Basisopdrachten</h2>
<section id="pwd-print-working-directory" class="level3">
<h3 class="anchored" data-anchor-id="pwd-print-working-directory"><code>pwd</code> (Print Working Directory)</h3>
<p>Toont je huidige locatie in het bestandssysteem.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> pwd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">/home/gebruikersnaam</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="ls-list" class="level3">
<h3 class="anchored" data-anchor-id="ls-list"><code>ls</code> (List)</h3>
<p>Geeft een lijst van bestanden en mappen in de huidige directory.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> ls</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Documenten</span>  Downloads  Afbeeldingen  Muziek</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Opties:</p>
<ul>
<li><code>ls -l</code>: Lang formaat, toont meer details zoals de eigenaar van het bestand en de bestandsgrootte in bytes.</li>
<li><code>ls -a</code>: Toont verborgen bestanden (die beginnen met een punt)</li>
<li><code>ls -lh</code>: Toont de grootte van de bestanden (in de kolom) in een eenvoudig formaat (<code>K</code>: kilobyte, <code>M</code>: megabyte, <code>G</code>: gigabyte).</li>
</ul>
</section>
<section id="cd-change-directory" class="level3">
<h3 class="anchored" data-anchor-id="cd-change-directory"><code>cd</code> (Change Directory)</h3>
<p>Verplaatst je naar een andere directory.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> cd Documenten</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Speciale directories:</p>
<ul>
<li><code>.</code> : Huidige directory</li>
<li><code>..</code>: Bovenliggende directory</li>
<li><code>~</code> : Thuisdirectory van de gebruiker</li>
</ul>
</section>
<section id="mkdir-make-directory" class="level3">
<h3 class="anchored" data-anchor-id="mkdir-make-directory"><code>mkdir</code> (Make Directory)</h3>
<p>Maakt een nieuwe directory aan.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> mkdir NieuweMap</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="cp-copy" class="level3">
<h3 class="anchored" data-anchor-id="cp-copy"><code>cp</code> (Copy)</h3>
<p>Kopieert bestanden of directories.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> cp bestand.txt Documenten/</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Om een directory en zijn inhoud te kopiëren, gebruik de <code>-r</code> (recursief) optie:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> cp <span class="at">-r</span> MapA MapB</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="mv-move" class="level3">
<h3 class="anchored" data-anchor-id="mv-move"><code>mv</code> (Move)</h3>
<p>Verplaatst of hernoemt bestanden en directories.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> mv bestand.txt Documenten/</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> mv oudenaam.txt nieuwenaam.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="rm-remove" class="level3">
<h3 class="anchored" data-anchor-id="rm-remove"><code>rm</code> (Remove)</h3>
<p>Verwijdert bestanden of directories. Wees voorzichtig met deze opdracht!</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> rm bestand.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Om een directory en zijn inhoud te verwijderen, gebruik de <code>-r</code> optie:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> rm <span class="at">-r</span> MapNaam</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="cat-concatenate" class="level3">
<h3 class="anchored" data-anchor-id="cat-concatenate"><code>cat</code> (Concatenate)</h3>
<p>Toont de inhoud van een bestand.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> cat bestand.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="echo" class="level3">
<h3 class="anchored" data-anchor-id="echo"><code>echo</code></h3>
<p>Print tekst naar het scherm.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> echo <span class="st">"Hallo, Wereld!"</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Hallo,</span> Wereld!</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="opdrachtstructuur" class="level2">
<h2 class="anchored" data-anchor-id="opdrachtstructuur">Opdrachtstructuur</h2>
<p>De meeste opdrachten volgen deze structuur:</p>
<pre><code>opdracht [opties] [argumenten]</code></pre>
<p>Bijvoorbeeld:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> ls <span class="at">-l</span> Documenten</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Hier is <code>ls</code> de opdracht, <code>-l</code> een optie, en <code>Documenten</code> een argument.</p>
</section>
<section id="tips" class="level2">
<h2 class="anchored" data-anchor-id="tips">Tips</h2>
<ol type="1">
<li>Gebruik de pijltjestoetsen omhoog en omlaag om door je opdrachtgeschiedenis te navigeren.</li>
<li>Gebruik Tab voor automatische aanvulling van bestands- en mapnamen.</li>
<li>Gebruik <code>man</code> gevolgd door een opdrachtnaam om de handleiding te zien (bijv. <code>man ls</code>).</li>
</ol>
</section>
<section id="oefenopdrachten" class="level2">
<h2 class="anchored" data-anchor-id="oefenopdrachten">Oefenopdrachten</h2>
<blockquote class="blockquote">
<p>Deze opdrachten dienen louter om jezelf vertrouwd te maken met een Linux shell, ze maken geen deel uit van het verslag.</p>
</blockquote>
<ol type="1">
<li>Maak een directory genaamd “BioinformaticaCursus” in je thuisdirectory.</li>
<li>Maak binnen “BioinformaticaCursus” drie subdirectories: “Data”, “Scripts” en “Resultaten”.</li>
<li>Maak een leeg bestand genaamd “notities.txt” in de “BioinformaticaCursus” directory.</li>
<li>Toon de inhoud van “BioinformaticaCursus” in lang formaat.</li>
<li>Verplaats “notities.txt” naar de “Resultaten” directory.</li>
<li>Kopieer “notities.txt” van “Resultaten” naar “Data”.</li>
<li>Verwijder het “notities.txt” bestand uit de “Data” directory.</li>
</ol>
</section>
</section>
<section id="kwaliteitscontrole-met-fastqc" class="level1">
<h1>Kwaliteitscontrole met FastQC</h1>
<section id="doel" class="level2">
<h2 class="anchored" data-anchor-id="doel">Doel</h2>
<p>Het hoofddoel van FastQC is om een snelle kwaliteitscontrole uit te voeren op ruwe sequentiedata afkomstig van high-throughput sequencing pijplijnen (FASTQ formaat). Het helpt bij het identificeren van problemen die kunnen voortkomen uit de sequencer zelf of de bibliotheekvoorbereiding.</p>
</section>
<section id="het-fastq-formaat" class="level2">
<h2 class="anchored" data-anchor-id="het-fastq-formaat">Het FASTQ-formaat</h2>
<section id="wat-is-fastq" class="level3">
<h3 class="anchored" data-anchor-id="wat-is-fastq">Wat is FASTQ?</h3>
<p>FASTQ is een tekstbestandsformaat voor het opslaan van zowel nucleotidensequenties (reads) als hun corresponderende kwaliteitsscores. Het wordt veel gebruikt voor het opslaan van gegevens die afkomstig zijn van sequencing-apparaten.</p>
</section>
<section id="voorbeeld-van-een-fastq-entry" class="level3">
<h3 class="anchored" data-anchor-id="voorbeeld-van-een-fastq-entry">Voorbeeld van een FASTQ-entry</h3>
<pre><code>@SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF&gt;&gt;&gt;&gt;&gt;&gt;CCCCCCC65</code></pre>
</section>
<section id="structuur-van-een-fastq-bestand" class="level3">
<h3 class="anchored" data-anchor-id="structuur-van-een-fastq-bestand">Structuur van een FASTQ-bestand</h3>
<p>Een FASTQ-bestand bestaat uit blokken van vier regels per sequentie:</p>
<ol type="1">
<li>Een regelbeginlijn die start met ‘@’, gevolgd door een sequentie-identifier</li>
<li>De ruwe sequentiegegevens</li>
<li>Een regel die begint met ‘+’, optioneel gevolgd door dezelfde sequentie-identifier</li>
<li>De <em>Phred</em> kwaliteitsscores voor de sequentie in gecodeerde vorm, één karakter per nucleotide.</li>
</ol>
<p>Een kwaliteitsscore is de kans dat de nucleotide op die positie foutief gecalled werd. De relatie tussen de score <span class="math inline">\(Q\)</span> en de kans <span class="math inline">\(P\)</span> wordt gegeven door onderstaande formule:</p>
<p><span class="math display">\[
P = 10^{\frac{-Q}{10}}
\]</span></p>
<p>Zo staat <code>(</code> voor een <em>Pred</em> score van 7 wat overeen komt met een kans van 20% op een foutieve call. Hoe zuiverder het signaal is de sequencer, hoe zekerder de call. Het staal, de staal- of bibliotheekvoorbereiding en de sequencing(reagentia) kunnen aanleiding geven tot minder kwalitatieve data. Die slechte kwaliteit zal in de verdere bio-informatica analyse resulteren in een slecht of onbetrouwbaar resultaat. Daarom is de eerste stap in een bio-informatica analyse van sequencing data een kwaliteitscontrole op basis van de <em>Phred</em> kwaliteitsscores is de FASTQ bestanden. Het FastQC programma berekend samenvattende statistieken over alle entries in een FASTQ bestand en geeft deze weer in een rapport.</p>
</section>
</section>
<section id="opdrachten" class="level2">
<h2 class="anchored" data-anchor-id="opdrachten">Opdrachten</h2>
<p>Voer volgende commando’s uit in de VS Code terminal.</p>
<p>Op de VSC infrastructuur is er bijzonder veel software geïnstalleerd en beschikbaar voor gebruik. Vooraleer we een bepaald software programma kunnen gebruiken moeten het wel nog inladen via het <code>module</code> commando. Na het inladen blijft de software de hele sessie beschikbaar.</p>
<p>Laad de FastQC module</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load FastQC/0.11.8-Java-1.8.0_162</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Voer FastQC uit op één FASTQ read-bestand</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="ex">fastqc</span> naam_van_fastq_bestand.fastq.gz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<blockquote class="blockquote">
<p>Pas de naam van het FASTQ bestand aan naar de naam van jouw bestand in het bovenstaande commando.</p>
</blockquote>
<p>Het FastQC rapport wordt gegenereerd, dit duurt enkele seconden. Hierna zie je het rapport (bv <code>naam_van_fastq_bestand_fastqc.html</code>) verschijnen in de linkerbalk. Om het rapport te openen moeten we het eerst downloaden (rechtsklikken + download).</p>
</section>
<section id="het-interpreteren-van-het-fastqc-html-rapport" class="level2">
<h2 class="anchored" data-anchor-id="het-interpreteren-van-het-fastqc-html-rapport">Het interpreteren van het FastQC HTML-rapport</h2>
<ol type="1">
<li><p><strong>Basic Statistics</strong>: Geeft een overzicht van het bestand, waaronder totaal aantal sequenties, sequentielengte en GC-gehalte.</p></li>
<li><p><strong>Per base sequence quality</strong>: Toont hoe de kwaliteitsscores (Phred scores) verlopen over de lengte van de reads. De blauwe lijn geeft de gemiddelde kwaliteitsscore mee over alle reads. Normaal neemt de kwaliteitsscore af met de lengte van de reads. Bij een goede gelukte sequencing blijft het gemiddelde ook naar het einde van de reads toe voldoende hoog.</p>
<ul>
<li>Groen gebied: Goede kwaliteit</li>
<li>Oranje gebied: Redelijke kwaliteit</li>
<li>Rood gebied: Slechte kwaliteit</li>
</ul></li>
<li><p><strong>Per sequence quality scores</strong>: Geeft de verdeling van kwaliteitsscores over alle sequenties. We verwachten een normale verdeling met een gemiddelde hoger dan 30.</p></li>
<li><p><strong>Per base sequence content</strong>: Toont de verhoudingen van basen op elke positie.</p></li>
<li><p><strong>Per sequence GC content</strong>: Vergelijkt de waargenomen GC-inhoudverdeling met een theoretische normale verdeling.</p></li>
<li><p><strong>Per base N content</strong>: Toont het percentage van basen op elke positie die niet konden worden bepaald (N).</p></li>
<li><p><strong>Sequence Length Distribution</strong>: Voor de meeste platformen zou dit een scherpe piek moeten zijn.</p></li>
<li><p><strong>Sequence Duplication Levels</strong>: Hoge duplicatieniveaus kunnen duiden op PCR-bias.</p></li>
<li><p><strong>Overrepresented sequences</strong>: Lijst van sequenties die vaker voorkomen dan verwacht.</p></li>
<li><p><strong>Adapter Content</strong>: Toont de aanwezigheid van vaak gebruikte adapters in je bibliotheek.</p></li>
</ol>
</section>
<section id="opdrachtvragen" class="level2">
<h2 class="anchored" data-anchor-id="opdrachtvragen">Opdrachtvragen:</h2>
<ol type="1">
<li>Hoeveel sequenties/reads zijn er in het FASTQ bestand aanwezig?</li>
<li>Wat is de gemiddelde kwaliteitsscore over alle basen en reads? Geef ook de interpretatie van deze score.</li>
<li>Hoe verandert de kwaliteitsscore over de lengte van de reads?</li>
</ol>
</section>
</section>
<section id="read-mapping-met-bwa" class="level1">
<h1>Read Mapping met BWA</h1>
<section id="doel-1" class="level2">
<h2 class="anchored" data-anchor-id="doel-1">Doel</h2>
<p>In deze stap worden de sequenties in de FASTQ-bestanden uitgelijnd (gealigneerd) met een referentiegenoom. Het resultaat zal de meest waarschijnlijke oorsprong van de read zijn alsook op welke manier deze verschilt van het referentie genoom. Dit proces gebruikt algoritmen om te bepalen waar elke read het best past op het referentiegenoom. Het resultaat van deze alignment wordt opgeslagen in SAM- of BAM-formaat. BWA (Burrows-Wheeler Aligner) is een veelgebruikte tool om reads te aligneren tegen een referentiegenoom.</p>
</section>
<section id="sam-formaat-sequence-alignmentmap" class="level2">
<h2 class="anchored" data-anchor-id="sam-formaat-sequence-alignmentmap">SAM-formaat (Sequence Alignment/Map)</h2>
<section id="wat-is-sam" class="level3">
<h3 class="anchored" data-anchor-id="wat-is-sam">Wat is SAM?</h3>
<p>SAM is een tekstbestandsformaat voor het opslaan van sequentie-alignments. Het wordt gebruikt om te beschrijven hoe sequenties zijn uitgelijnd ten opzichte van een referentiegenoom.</p>
</section>
<section id="structuur-van-een-sam-bestand" class="level3">
<h3 class="anchored" data-anchor-id="structuur-van-een-sam-bestand">Structuur van een SAM-bestand</h3>
<p>Een SAM-bestand bestaat uit: - Een optionele headergedeelte (regels die beginnen met @) - Alignment-gedeelte met één regel per alignment</p>
</section>
<section id="voorbeeld-van-een-sam-entry" class="level3">
<h3 class="anchored" data-anchor-id="voorbeeld-van-een-sam-entry">Voorbeeld van een SAM-entry</h3>
<pre><code>@SQ     SN:chr1 LN:248956422
...
@RG     ID:simulated_data_3     SM:simulated_data_3
@PG     ID:bwa  PN:bwa  VN:0.7.17-r1188 CL:bwa mem -R @RG\tID:simulated_data_3\tSM:simulated_data_3 /staging/leuven/stg_00156/references/hg38.fa simulated_data_3.fastq.gz
SEQ_ID  0  chr12  120999772  60  101M  *  0  0  GGGGTGGGGT...  TG  FFF:FFFFF...  NM:i:0  MD:Z:101  AS:i:101  XS:i:19  RG:Z:simulated_data_3</code></pre>
</section>
<section id="uitleg" class="level3">
<h3 class="anchored" data-anchor-id="uitleg">Uitleg</h3>
<p>We overlopen even de belangrijkste velden in het SAM formaat</p>
<ol type="1">
<li><code>SEQ_ID</code> - Dit is de identifier van de read/sequentie.</li>
<li><code>0</code> - Dit is de FLAG waarde. Een 0 betekent:
<ul>
<li>De read is unpaired</li>
<li>De read is gealigneerd naar de forward strand</li>
<li>Geen andere speciale eigenschappen</li>
</ul></li>
<li><code>chr12</code> - De naam van het referentie chromosoom waar de read naartoe gemapt is.</li>
<li><code>120999772</code> - De startpositie van de alignment op het referentie chromosoom (1-based).</li>
<li><code>60</code> - De mapping quality score (MAPQ). Een score van 60 is zeer hoog en geeft aan dat de aligner zeer zeker is van deze mapping positie.</li>
<li><code>101M</code> - De CIGAR string. <code>101M</code> betekent dat alle 101 bases van de read perfect aligneren met het referentiegenoom (M = match of mismatch).</li>
<li><code>GGGGTGGGGT...</code> - De read sequentie (hier afgekort met …).</li>
<li><code>FFF:FFFFF...</code> - De kwaliteitsscores in <em>Phred</em> formaat (hier afgekort).</li>
</ol>
<p>De optionele velden aan het eind: - <code>NM:i:0</code> - Aantal mismatches in de alignment (hier 0, perfect match) - <code>MD:Z:101</code> - String die exact beschrijft waar mismatches zitten. 101 betekent 101 matches achter elkaar - <code>AS:i:101</code> - Alignment score (101 is hoog, goede alignment) - <code>XS:i:19</code> - Secundaire alignment score (score van de op-één-na beste alignment positie)</p>
<p>Dit is duidelijk een zeer goede alignment want: - Hoge MAPQ score (60) - Perfect match (NM:i:0) - Grote alignment score (AS:i:101) - Groot verschil tussen beste en tweede beste alignment (AS:i:101 vs XS:i:19)</p>
<blockquote class="blockquote">
<p>In de praktijk gaan we de alignments in een SAM bestand nooit manueel inspecteren maar zullen we samenvattende statistieken berekenen zoals <code>fastqc</code> doet met een FASTQ bestand.</p>
</blockquote>
</section>
</section>
<section id="opdrachten-1" class="level2">
<h2 class="anchored" data-anchor-id="opdrachten-1">Opdrachten</h2>
<p>Laad de BWA module</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load BWA/0.7.17-GCC-10.3.0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Aligneer de reads met volgende commando’s.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We slaan eerst de bestandslocatie van het referentiegenoom op in een variabele REF</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="va">REF</span><span class="op">=</span>/staging/leuven/stg_00156/references/hg38.fa</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># We voeren nu BWA uit en schrijven de output weg naar aligned.sam</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="ex">bwa</span> mem <span class="at">-R</span> <span class="st">'@RG\tID:samplename\tSM:samplename'</span> <span class="va">$REF</span> naam_van_fastq_bestand.fastq.gz <span class="op">&gt;</span> mijn_staal.sam</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<blockquote class="blockquote">
<p>Pas de naam van het FASTQ bestand aan naar de naam van jouw bestand in het bovenstaande commando. Pas ook de naam van output bestand aan naar bv de naam van je groepje.</p>
</blockquote>
<blockquote class="blockquote">
<p>De optie <code>-R '@RG\tID:samplename\tSM:samplename'</code> voegt een staalnaam en ID toe aan het SAM bestand. Dit is noodzakelijk voor sommige software programma’s die we later zullen gebruiken.</p>
</blockquote>
</section>
<section id="bam-formaat-binary-alignmentmap" class="level2">
<h2 class="anchored" data-anchor-id="bam-formaat-binary-alignmentmap">BAM-formaat (Binary Alignment/Map)</h2>
<section id="wat-is-bam" class="level3">
<h3 class="anchored" data-anchor-id="wat-is-bam">Wat is BAM?</h3>
<p>BAM is de binaire versie van het SAM-formaat. Het bevat dezelfde informatie als SAM, maar in een gecomprimeerde, binaire vorm. Bestanden zijn dus een stuk kleiner en dat spaart ruimte bij het archiveren en tijd bij het kopiëren van bestanden. Om BAM files efficient te kunnen verwerken worden de reads vaak gesorteerd volgens positie in het referentiegenoom en wordt er een index aangemaakt. Dit maakt de vervolgstappen een stuk sneller.</p>
</section>
<section id="kenmerken-van-bam" class="level3">
<h3 class="anchored" data-anchor-id="kenmerken-van-bam">Kenmerken van BAM</h3>
<ul>
<li>Neemt minder opslagruimte in beslag dan SAM</li>
<li>Sneller te verwerken door computers</li>
<li>Kan worden geïndexeerd voor snelle toegang tot specifieke regio’s</li>
</ul>
</section>
<section id="voorbeeld" class="level3">
<h3 class="anchored" data-anchor-id="voorbeeld">Voorbeeld</h3>
<p>Omdat BAM een binair formaat is, kunnen we geen leesbaar voorbeeld geven zoals bij SAM. In de praktijk kan je speciale software gebruiken om BAM-bestanden te bekijken of te bewerken.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="cursus_images/igv_snapshot.png" class="img-fluid figure-img"></p>
<figcaption>BAM file gevisualiseerd met Integrative Genomics Viewer (IGV).</figcaption>
</figure>
</div>
<p>Bovenstaande figuur is een screenshot gemaakt met Integrative Genomics Viewer (IGV), een populair programma om BAM files en andere genomische databestanden weer te geven t.o.v. een referentiegenoom. De grijze balken zijn de reads gepositioneerd t.o.v. het referentiegenoom. Op de gekleurde posities verschilt de read sequentie van het referentiegenoom.</p>
</section>
</section>
<section id="opdracht-2" class="level2">
<h2 class="anchored" data-anchor-id="opdracht-2">Opdracht 2</h2>
<p>Zet het SAM bestand om naar een gesorteerd BAM bestand met <code>samtools</code>.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load SAMtools/1.13-GCC-10.3.0</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Sorteer het BAM bestand en sla het gesorteerde bestand op onder een nieuwe naam</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="ex">samtools</span> sort mijn_staal.sam <span class="at">-o</span> mijn_staal.sorted.bam</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Indexeer het gesorteerde BAM bestand. De index wordt opgeslagen als NAAM_VAN_BAM.bai</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="ex">samtools</span> index mijn_staal.sorted.bam</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Met <code>samtools flagstat</code> kan je een aantal eenvoudige statistieken van het BAM bestand berekenen.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="ex">samtools</span> flagstat mijn_staal.sorted.bam</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="opdrachtvragen-1" class="level2">
<h2 class="anchored" data-anchor-id="opdrachtvragen-1">Opdrachtvragen:</h2>
<ol type="1">
<li>Wat is de bestandsgrootte van het SAM en BAM bestand?</li>
<li>Hoeveel reads zijn er gealigneerd tegen het referentiegenoom?</li>
<li>Wat is het percentage van de totaal aantal reads die gealigneerd zijn?</li>
<li>Kan je redenen bedenken waarom een read niet met het referentiegenoom aligneerd? (Meerdere mogelijkheden)</li>
</ol>
</section>
</section>
<section id="variant-calling-met-mutect2" class="level1">
<h1>Variant Calling met Mutect2</h1>
<p>Variant calling is het proces waarbij we verschillen (varianten) identificeren tussen een sequentiedataset en een referentiegenoom. Het is een cruciale stap in veel genomische analyses, van het bestuderen van genetische ziekten tot het begrijpen van evolutie. De meeste software tools voor Variant Calling vertrekken van uitgelijnde reads in het BAM formaat. Door op elke positie in het referentiegenoom de uitgelijnde reads te vergelijken zal de software varianten kunnen opsporen. Mutect2 is een veelgebruikte bio-informatica tool om somatische varianten te identificeren uit de uitgelijnde reads.</p>
<p>Wanneer er een verschil met het referentiegenoom gevonden wordt, wil dit nog niet noodzakelijk zeggen dat het om een werkelijke variant in het staal gaat. Sequencing fouten of problemen met de alignment kunnen ook zulke verschillen veroorzaken. De kwaliteitsscores in de reads vormen hier een belangrijk hulpmiddel voor de software. Twee belangrijke statistieken die gebruikt worden om “echte” varianten van vals positieve te onderscheiden zijn de <em>depth</em>, het aantal reads dat overlapt met de positie van de variant, en de <em>allele frequency</em>, het percentage van de reads waar de variant werd teruggevonden. Afhankelijk van de gebruikte technologie wordt een minimale <em>depth</em> en <em>allele frequency</em> voorop gesteld. Als de variant onder deze waarden valt wordt deze als vals positief beschouwd.</p>
<section id="vcf-formaat-variant-call-format" class="level2">
<h2 class="anchored" data-anchor-id="vcf-formaat-variant-call-format">VCF-formaat (Variant Call Format)</h2>
<section id="wat-is-vcf" class="level3">
<h3 class="anchored" data-anchor-id="wat-is-vcf">Wat is VCF?</h3>
<p>VCF is een tekstbestandsformaat voor het opslaan van genoomvariaties zoals SNPs, inserties, deleties en structurele varianten. Alle genoomvariaties worden weergegeven ten opzichte van het gekozen referentiegenoom.</p>
</section>
<section id="structuur-van-een-vcf-bestand" class="level3">
<h3 class="anchored" data-anchor-id="structuur-van-een-vcf-bestand">Structuur van een VCF-bestand</h3>
<p>Een VCF-bestand bestaat uit: - Meta-informatieregels (beginnen met ##) - Een headerregel (begint met #) - Dataregels met informatie over elke variant</p>
</section>
<section id="voorbeeld-van-een-vcf-entry" class="level3">
<h3 class="anchored" data-anchor-id="voorbeeld-van-een-vcf-entry">Voorbeeld van een VCF-entry</h3>
<pre><code>##fileformat=VCFv4.3
#CHROM POS ID REF ALT QUAL FILTER INFO
20 14370 rs6054257 G A 29 PASS NS=3;DP=14;AF=0.5;DB;H2</code></pre>
</section>
<section id="uitleg-1" class="level3">
<h3 class="anchored" data-anchor-id="uitleg-1">Uitleg</h3>
<ul>
<li>CHROM: Chromosoom</li>
<li>POS: Positie van de variant</li>
<li>ID: Optionele variant identifier (bijv. rs-nummer van gekende varianten in de dbSNP databank)</li>
<li>REF: Referentie-allel zoals het in het referentiegenoom aanwezig is</li>
<li>ALT: Alternatief allel dat gevonden werd in het staal</li>
<li>QUAL: Kwaliteitsscore</li>
<li>FILTER: Filter status (PASS betekent dat de variant alle filters heeft gepasseerd)</li>
<li>INFO: Aanvullende informatie over de variant zoals de <em>depth</em> (<code>DP</code>) en de <em>allele frequency</em> (<code>AF</code>)</li>
</ul>
</section>
</section>
<section id="opdrachten-2" class="level2">
<h2 class="anchored" data-anchor-id="opdrachten-2">Opdrachten</h2>
<p>Voer variant calling uit met Mutect2 op de gesorteerde BAM file.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load GATK/4.1.9.0-foss-2018a-Java-11.0.4</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="va">REF</span><span class="op">=</span>/staging/leuven/stg_00156/references/hg38.fa</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="ex">gatk</span> Mutect2 <span class="dt">\</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">-R</span> <span class="va">$REF</span> <span class="dt">\</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">-I</span> mijn_staal.sorted.bam <span class="dt">\</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">-O</span> mijn_staal.vcf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="opdrachtvragen-2" class="level2">
<h2 class="anchored" data-anchor-id="opdrachtvragen-2">Opdrachtvragen:</h2>
<ol type="1">
<li>Wat is de bestandsgrootte van het VCF bestand?</li>
<li>Kan je intuïtief uitleggen waarom het VCF bestand veel kleiner is dan een SAM/BAM bestand?</li>
</ol>
<p>Open nu de aangemaakte VCF file in VS Code en beantwoord volgende vragen. Bovenaan in het bestand staan er ongeveer 500 meta-informatieregels (beginnen met <code>##</code>). Deze mag je negeren en verder scrollen naar de regel die begint met <code>#CHROM</code>. Hieronder staan alle varianten, één per regel.</p>
</section>
<section id="opdrachtvragen-deel-2" class="level2">
<h2 class="anchored" data-anchor-id="opdrachtvragen-deel-2">Opdrachtvragen deel 2:</h2>
<ol type="1">
<li>Hoeveel varianten werden er gevonden in je staal?</li>
<li>Bestudeer de eerste variant in het VCF bestand.
<ul>
<li>Op welk chromosoom en positie is de variant gevonden?</li>
<li>Wat is de sequentie in het referentie genoom?</li>
<li>Wat is de sequentie in het staal?</li>
<li>Wat zijn de <em>depth</em> en <em>allele frequency</em> van de variant?</li>
</ul></li>
</ol>
</section>
</section>
<section id="variant-annotatie-met-snpeff" class="level1">
<h1>Variant Annotatie met SnpEff</h1>
<p>In het VCF bestand dat je bekomen bent bij de vorige stap zitten bijzonder veel varianten. De overgrote meerderheid heeft geen belangrijke impact omdat ze bijvoorbeeld in intergenische regio’s of intronen liggen of synonieme mutaties zijn (geen verandering in aminozuursequentie). Het identificeren van één of enkele varianten die aan de basis van een ziektebeeld liggen (zoals kanker) is dus een zoektocht naar een speld in een hooiberg! Een belangrijk hulpmiddel in deze zoektocht is <em>variant annotatie</em> waarbij we voor elke variant de impact op het eiwit gaan bepalen. Een veelgebruikte tool hiervoor is snpEff. SnpEff maakt gebruik van een databank die gen en eiwitposities ten opzicht van het referentiegenoom bevat. Op die manier kan de impact van een variant op de eiwitsequentie bepaald worden.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load snpEff/5.2c-GCCcore-10.3.0-Java-11</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># de bestandslocatie van de snpeff databank slaan we op in een variabele</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="va">SNPEFF_REF</span><span class="op">=</span>/staging/leuven/stg_00156/references/snpEff</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># we voeren snpeff uit op ons VCF bestand en slaan de output op in een nieuw VCF bestand</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="ex">snpEff</span> <span class="at">-dataDir</span> <span class="va">$SNPEFF_REF</span> hg38 input_varianten.vcf <span class="op">&gt;</span> varianten.annotated.vcf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Open de geannoteerde VCF in VS Code. Kijk naar het <code>ANN=</code> veld in de output VCF voor gedetailleerde annotaties. In dit veld staat de annotatie van deze variant als volgt:</p>
<section id="het-snpeff-html-rapport-begrijpen" class="level2">
<h2 class="anchored" data-anchor-id="het-snpeff-html-rapport-begrijpen">Het SnpEff HTML-rapport begrijpen</h2>
<p>SnpEff genereert naast geannoteerde varianten ook een uitgebreid HTML-rapport met statistieken en visualisaties (<code>snpEff_summary.html</code>). Download het bestand en open het in je browser. Laten we nu dit stap voor stap doornemen.</p>
<section id="a.-algemene-statistieken-sectie" class="level3">
<h3 class="anchored" data-anchor-id="a.-algemene-statistieken-sectie">A. Algemene Statistieken Sectie</h3>
<ol type="1">
<li><strong>Variants rate details</strong>:
<ul>
<li>Aantal varianten per chromosoom</li>
<li>Totaal aantal verwerkte varianten</li>
</ul></li>
<li><strong>Number variants by type</strong>:
<ul>
<li>SNP (Single Nucleotide Polymorphisms)</li>
<li>MNP (Multiple Nucleotide Polymorphisms)</li>
<li>INS (Inserties)</li>
<li>DEL (Deleties)</li>
</ul></li>
<li><strong>Number of effects by impact</strong>:
<ul>
<li>HIGH: Grote impact op genfunctie (bijvoorbeeld stopcodons)</li>
<li>MODERATE: Mogelijk effect op genfunctie (bijvoorbeeld missense varianten)</li>
<li>LOW: Waarschijnlijk geen effect op genfunctie (bijvoorbeeld synonyme varianten)</li>
<li>MODIFIER: Meestal in niet-coderende regio’s</li>
</ul></li>
<li><strong>Number of effects by functional class</strong>:
<ul>
<li>Missense</li>
<li>Nonsense</li>
<li>Silent</li>
<li>Splice site variants</li>
<li>etc.</li>
</ul></li>
</ol>
</section>
</section>
<section id="opdrachtvragen-3" class="level2">
<h2 class="anchored" data-anchor-id="opdrachtvragen-3">Opdrachtvragen</h2>
<section id="deel-1-basis-statistieken" class="level3">
<h3 class="anchored" data-anchor-id="deel-1-basis-statistieken">Deel 1: Basis Statistieken</h3>
<p>Open het SnpEff HTML-rapport voor je geannoteerde varianten en beantwoord de volgende vragen:</p>
<ol type="1">
<li>Hoeveel varianten zijn er in totaal geanalyseerd?</li>
<li>Wat is de verdeling tussen SNPs, inserties en deleties?</li>
<li>Welk chromosoom heeft de meeste varianten?</li>
<li>Bereken het percentage varianten dat als ‘HIGH impact’ is geclassificeerd.</li>
</ol>
</section>
<section id="deel-2-variant-effects-analyse" class="level3">
<h3 class="anchored" data-anchor-id="deel-2-variant-effects-analyse">Deel 2: Variant Effects Analyse</h3>
<p>Bekijk de ‘Number of effects by type and region’ sectie:</p>
<ol type="1">
<li>Wat zijn de top 3 meest voorkomende effecten?</li>
<li>Hoeveel missense varianten zijn er gevonden?</li>
<li>Hoeveel splice site varianten zijn er?</li>
</ol>
</section>
<section id="deel-3-genoomregios" class="level3">
<h3 class="anchored" data-anchor-id="deel-3-genoomregios">Deel 3: Genoomregio’s</h3>
<p>Bestudeer de ‘Region counts’ tabel:</p>
<ol type="1">
<li>Welk percentage van de varianten ligt in:
<ul>
<li>Exonen?</li>
<li>Intronen?</li>
<li>Intergene regio’s?</li>
</ul></li>
<li>Is deze verdeling wat je zou verwachten? Waarom wel/niet?</li>
</ol>
</section>
<section id="deel-4-codon-veranderingen" class="level3">
<h3 class="anchored" data-anchor-id="deel-4-codon-veranderingen">Deel 4: Codon Veranderingen</h3>
<p>Analyseer de ‘Codon Changes’ sectie:</p>
<ol type="1">
<li>Wat zijn de meest voorkomende codon veranderingen?</li>
<li>Hoeveel stop-gained mutaties zijn er?</li>
<li>Zijn er bepaalde aminozuur veranderingen die vaker voorkomen dan andere?</li>
</ol>
</section>
</section>
</section>
<section id="variant-filtering-met-snpsift" class="level1">
<h1>Variant filtering met SnpSift</h1>
<p>Nadat we een geannoteerde VCF file hebben bekomen kunnen op basis van deze annotatie varianten filteren. Gezien de grote hoeveelheid varianten die typisch gevonden worden in een sequencing experiment is dit een cruciale stap.</p>
<p>Gebruik volgende commando om alle varianten met een <em>allele frequency</em> groter dan 50% met een hoge impact te filteren en in een nieuw bestand op te slaan.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="va">SNPSIFT_JAR</span><span class="op">=</span>/vsc-hard-mounts/leuven-apps/rocky8/skylake/2021a/software/snpEff/5.2c-GCCcore-10.3.0-Java-11/SnpSift.jar</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="ex">java</span> <span class="at">-jar</span> <span class="va">$SNPSIFT_JAR</span> filter <span class="st">"( GEN[*].AF &gt; 0.50 ) &amp; ( ANN[*].IMPACT = 'HIGH' )"</span> varianten.annotated.vcf <span class="op">&gt;</span> varianten.annotated.filtered.vcf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>VCF bestanden zijn moeilijk te interpreteren na toevoegen van de annotatie door de grote hoeveelheid informatie die erin staat. Met het onderstaande commando kan je alle varianten in het gefilterde VCF bestand in een overzichtelijke tabel weergeven.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="ex">java</span> <span class="at">-jar</span> <span class="va">$SNPSIFT_JAR</span> extractFields <span class="at">-s</span> <span class="st">","</span> <span class="at">-e</span> <span class="st">"."</span> varianten.annotated.filtered.vcf CHROM POS REF ALT <span class="st">"ANN[0].GENE"</span> <span class="st">"ANN[0].EFFECT"</span> <span class="st">"ANN[0].HGVS_C"</span> <span class="st">"ANN[0].HGVS_P"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="opdrachtvragen-4" class="level2">
<h2 class="anchored" data-anchor-id="opdrachtvragen-4">Opdrachtvragen</h2>
<ol type="1">
<li>Hoeveel varianten hou je over na filtering.</li>
<li>In welke genen liggen deze varianten?</li>
<li>Wat is de sequentieverandering die de variant veroorzaakt in de transcriptsequentie en eiwitsequentie?</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>